---
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  FromDomain:
    Type: String
    Description: The domain a user is requesting.
  ToProtocol:
    Type: String
    Description: The protocol to prefix ToDomain.
    Default: https
  ToDomain:
    Type: String
    Description: The domain you would like your users to be redirected to.
  HostedZoneId:
    Type: String
    Description: The HostedZoneId of the ToDomain.
  FromDomainAcmArn:
    Type: String
    Description: The Arn of the FromDomain Certificate.
  ApiName:
    Type: String
    Default: Redirecter
  StageName:
    Type: String
    Default: v1

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Redirect all requests
      EndpointConfiguration:
        Types:
          - EDGE
      FailOnWarnings: false
      Name: !Ref ApiName

  ProxyResource:
    Type: AWS::ApiGateway::Resource
    DependsOn: RestApi
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt [RestApi, RootResourceId]
      PathPart: '{proxy+}'

  Method:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - RestApi
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !GetAtt [RestApi, RootResourceId]
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Lambda.Arn}/invocations

  MethodProxy:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - RestApi
      - ProxyResource
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Lambda.Arn}/invocations

  Stage:
    Type: AWS::ApiGateway::Stage
    DependsOn: RestApi
    Properties:
      DeploymentId: !Ref Deployment
      RestApiId: !Ref RestApi
      StageName: !Ref StageName

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: Stage
    Properties:
      ApiStages:
      -
        ApiId: !Ref RestApi
        Stage: !Ref StageName
      Description: Redirect
      UsagePlanName: redirect-all-requests

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: Method
    Properties:
      Description: Redirect Deployment
      RestApiId: !Ref RestApi

  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref FromDomainAcmArn
      DomainName: !Ref FromDomain
      EndpointConfiguration:
        Types:
          - EDGE

  BasePathMapping:
    DependsOn:
      - DomainName
      - RestApi
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref DomainName
      RestApiId: !Ref RestApi
      Stage: !Ref Stage

  RecordSetA:
    DependsOn: DomainName
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt [DomainName, DistributionDomainName]
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref HostedZoneId
      Name: !Join [ "", [ !Ref FromDomain, "." ] ]
      Type: A

  RecordSetAAAA:
    DependsOn: DomainName
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt [DomainName, DistributionDomainName]
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref HostedZoneId
      Name: !Join [ "", [ !Ref FromDomain, . ] ]
      Type: AAAA

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: >
          exports.handler = async (event) => {
              const redirectLoation = process.env.REDIRECT_DOMAIN + event.path;
              console.log('Redirecting from: ', event.headers.Referer || 'https://' +event.headers.Host + event.path, ' to: ', redirectLoation);
              return {
                isBase64Encoded: false,
                statusCode: 301,
                headers: {
                  'Content-Type': 'text/html',
                  'Location' : redirectLoation
                },
              };
          };
      Environment:
        Variables:
          REDIRECT_DOMAIN: !Join [ "", [ !Ref ToProtocol, "://", !Ref ToDomain ] ]
      Description: Redirects all web requests
      FunctionName: url-redirect
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: nodejs12.x
      Timeout: 5

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: basic-lambda-execution-role
      ManagedPolicyArns:
        - !Ref BasicLambdaExecutionPolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  BasicLambdaExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Basic Lambda Execution.
      ManagedPolicyName: basic-lambda-execution-managed-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Action: [ "logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents" ]
            Effect:  Allow
            Resource: "arn:aws:logs:*:*:*"

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Lambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*
